apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  namespace: vllm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
